// components/card/Background.vue
<template>
  <div
    class="card ultra-radius card-background flex-1 view-anchor mb-4"
    :class="[isDarkTheme ? 'hover-card-neon-yellow' : ' hover-card-uv']"
    style=""
    @mouseover="isHover = true"
    @mouseout="isHover = false"
  >
    <img
      :src="article.cover ? article.cover : article.imageHeader"
      class="hover-filter-cyberpunk-ix grad-filter"
      alt="teste"
      :class="
        isFeatured ? 'card-background-image-featured' : 'card-background-image'
      "
    />
    <div class="mask texture-mask-4"></div>
    <div
      class="card-img-overlay h-100 d-flex flex-column justify-content-end p-4"
    >
      <div class="d-flex align-items-center mb-2">
        <span
          class="marker-line py-1 bg-dark text-light"
          style="font-weight: 500"
        >
          {{ article.channel }}
        </span>
      </div>

      <h3 class="card-title">
        <span class="bg-dark text-light py-1">
          <span class="marker-line"> {{ article.title }} </span>
        </span>
      </h3>
      <!-- <div class="d-flex align-items-center mb-2">
        <span
          class="marker-line py-1 bg-dark text-light"
          style="font-weight: 500"
        >
          Por {{ article.author.name }} em {{ article.channel }}
        </span>
      </div> -->
      <div class="d-flex justify-content-between">
        <div class="d-flex align-items-center mt-1 mb-1">
          <div class="flex-shrink-0">
            <span class="visually-hidden-focusable">{{
              article.author.name
            }}</span>
            <img
              class="rounded-circle border border-dark"
              src="https://i.imgur.com/h4BIIOc.jpg"
              alt=""
              style="height: 48px; width: 48px; object-fit: cover"
            />
          </div>
          <div class="ms-2">
            <p class="text-sm font-medium text-light mb-0">
              <span class="marker-line bg-dark custom-padding">
                {{ article.author.name }}
              </span>
            </p>
            <div class="flex space-x-1 text-sm text-light">
              <time
                class="marker-line bg-dark text-capitalize custom-padding"
                dateTime="article.createdDate"
              >
                <DateFormat :date="article.createdDate" />
              </time>
            </div>
          </div>
        </div>
        <div class="d-flex align-items-end">
          <div class="">
            <nuxt-link
              :to="article.path"
              class="btn btn-read-more-sm"
              :class="isDarkTheme ? 'btn-neon-yellow' : 'btn-uv'"
            >
              Ler mais...
            </nuxt-link>
          </div>
        </div>
      </div>
      <!-- <div class="d-flex justify-content-between">
        <nuxt-link
          :to="article.path"
          class="btn btn-read-more-sm"
          :class="isDarkTheme ? 'btn-neon-yellow' : 'btn-uv'"
        >
          Ler mais...
        </nuxt-link>
      </div> -->
    </div>
  </div>
</template>
<script>
import { mapGetters } from "vuex";
export default {
  props: {
    article: {
      type: Object,
      default: null,
    },

    isFeatured: {
      type: Boolean,
      default: false,
    },

    badgeIsTag: {
      type: Boolean,
      default: false,
    },

    category: {
      type: Boolean,
      default: false,
    },

    tags: {
      type: Boolean,
      default: false,
    },
  },

  data() {
    return {
      isHover: false,
    };
  },

  computed: {
    ...mapGetters(["isDarkTheme"]),
  },

  methods: {
    slugName(data) {
      const link = data.replace("articles/", "").replace("/", "");
      return link;
    },
  },
};
</script>
<style lang="scss">
.ultra-radius {
  border-radius: 1.5rem !important;
}
.custom-padding {
  padding: 0.125rem 0.25rem !important;
}
</style>

// components/Cards/Background.jsx
import { useEffect, useState } from "react";
import { Card } from "@/types/card";
import Image from "next/image";
import Link from "next/link";
import DateFormat from "@/components/DateFormat";
import {
  Tooltip,
  TooltipContent,
  TooltipTrigger,
} from "@/components/ui/tooltip";

const CardBackground = ({ document, authors, isFeatured = false }) => {
  const [mounted, setMounted] = useState(false);

  const fallbackImage = "/images/blklight-thumb.jpg";

  let image;

  if (document.cover || document.imageHeader) {
    image = document.cover ? document.cover : document.imageHeader;
  } else {
    image = fallbackImage;
  }

  useEffect(() => setMounted(true), []);
  return (
    <div className="card card-background hover:hover-card !rounded-2xl hover:hover-card-uv hover:dark:hover-card-neon-yellow view-anchor">
      <img
        src={image}
        className={`!rounded-2xl ${document.filter} ${
          isFeatured
            ? "card-background-image-featured"
            : "card-background-image"
        }`}
        alt={`${document.title} image`}
      />
      <div className="mask texture-mask-4"></div>

      {/* <Image
        src={document.cover ? document.cover : document.imageHeader}
        className={`card-background-image-featured !rounded-2xl ${document.styles.filter}`}
        width={10000}
        height={10000}
        alt={`${document.title} image`}
      /> */}
      <div className="card-img-overlay flex flex-col">
        <div className="flex">
          <div className="flex items-center leading-normal !text-base">
            <span className="text-light-500 text-base font-medium bg-dark-500 !py-1">
              <span className="marker-line">
                <DateFormat date={document.date} />
              </span>
            </span>
          </div>
        </div>
      </div>
      <div className="card-img-overlay flex flex-col justify-end">
        <div className="flex items-center mb-2 leading-normal !text-base">
          <span className="marker-line !py-1 bg-dark-500 text-light-500 capitalize font-medium mr-2">
            {document.channel}
          </span>
          <span className="marker-line !py-1 bg-dark-500 text-light-500 capitalize font-medium">
            {document.category}
          </span>
        </div>

        <h3 className="card-title text-3xl">
          <Link className="" href={`/articles/${document.slug}`}>
            <span className="marker-line bg-dark-500 text-light-500 !py-1 hover:underline underline-offset-1">
              {document.title}
            </span>
          </Link>
        </h3>

        <div className="flex">
          {authors.map((author) => (
            <div key={author.name} className="flex items-center my-1">
              <div className="shrink-0">
                <Tooltip>
                  <TooltipTrigger asChild>
                    <img
                      id={`anchor-${author.slug}-${document.slug}`}
                      src={author.avatar}
                      className="w-[50px] h-[50px] object-cover rounded-full border border-dark-500 mr-2"
                      alt={`${author.name} avatar`}
                    />
                  </TooltipTrigger>
                  <TooltipContent align="center" side="right">
                    <p>{author.name}</p>
                  </TooltipContent>
                </Tooltip>
              </div>
            </div>
          ))}

          <div className="flex flex-1 items-center">
            <Link className="ml-auto" href={`/articles/${document.slug}`}>
              <button className="tracking-wider text-light-500 dark:text-dark-500 bg-uv-500 dark:bg-neon-yellow-500 hover:ring-2 ring-uv-300 dark:ring-neon-yellow-200 py-1 px-3 rounded font-medium transition-all !text-base">
                Ler mais...
              </button>
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
};
export default CardBackground;
