// components/card/Horizontal.vue
<template>
  <article
    class="card card-raised mb-4"
    :class="[isDarkTheme ? 'card-plain hover-card-yellow' : 'hover-card-uv']"
  >
    <div class="d-flex align-items-center px-3 py-3">
      <span
        class="badge bg-transparent border ms-0 me-2"
        :class="[
          isDarkTheme ? ' border-neon-yellow' : ' border-uv text-dark',
          badgeIsTag ? 'badge-tag' : '',
        ]"
      >
        <DateFormat :date="article.createdDate" />
      </span>
      <Badge :channel="article.channel" :isTag="badgeIsTag" />
    </div>
    <div class="d-sm-flex align-items-center px-3">
      <div class="flex-shrink-0">
        <img
          v-lazy="article.cover ? article.cover : article.imageHeader"
          :alt="article.title"
          class="card-image-h card-img-border hover-filter-cyberpunk-v"
          :class="isDarkTheme ? 'border-light' : 'border-dark'"
        />
      </div>
      <div class="flex-grow-1 ms-sm-3">
        <template v-if="category">
          <Badge
            :channel="article.channel"
            :category="article.category"
            isCategory
            class="mt-2"
          />
        </template>
        <h3 class="card-font-test my-2">
          {{ article.title }}
        </h3>

        <p class="d-xl-block d-lg-block d-sm-none mb-1">
          <template v-if="article.description">
            {{ article.description }}
          </template>
        </p>

        <p class="font-monospace mb-1">Por {{ article.author.name }}</p>
        <template v-if="tags">
          <div class="d-xl-block d-lg-block d-sm-none">
            <span
              v-for="tag in article.tags"
              :key="tag"
              class="badge bg-secondary text-dark"
            >
              {{ tag }}
            </span>
          </div>
        </template>
      </div>
    </div>
    <div class="d-flex align-items-center px-3 py-3">
      <NuxtLink
        :to="`${article.dir}/${article.slug}`"
        class="btn btn-raised btn-read-more-sm ms-auto"
        :class="isDarkTheme ? 'btn-neon-yellow' : 'btn-uv'"
      >
        Ler mais...
      </NuxtLink>
    </div>
  </article>
</template>
<script>
import { mapGetters } from "vuex";
export default {
  props: {
    article: {
      type: Object,
      default: null,
    },

    badgeIsTag: {
      type: Boolean,
      default: false,
    },

    category: {
      type: Boolean,
      default: false,
    },

    tags: {
      type: Boolean,
      default: false,
    },
  },

  computed: {
    ...mapGetters(["isDarkTheme"]),
  },

  methods: {
    slugName(data) {
      const link = data.replace("articles/", "").replace("/", "");
      return link;
    },
  },
};
</script>

<style lang="scss">
@import url("https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,400;0,700;1,400;1,700&display=swap");

.card-image-h {
  width: 350px;
  height: 250px;
  object-fit: cover;
}

@media screen and (max-width: 768px) {
  .card-image-h {
    width: 200px;
    height: 150px;
    object-fit: cover;
  }
}

@media screen and (max-width: 576px) {
  .card-image-h {
    width: 100%;
    height: 300px;
    object-fit: cover;
  }
}

.card-font-test {
  font-family: "Playfair Display", serif;
}
</style>

// components/Cards/Horizontal.tsx
import { useEffect, useState } from "react";
import Image from "next/image";
import Link from "next/link";
import { Card } from "@/types/card";
import DateFormat from "@/components/DateFormat";
import Tags from "@/components/Tags";
import {
  Tooltip,
  TooltipContent,
  TooltipTrigger,
} from "@/components/ui/tooltip";

const CardHorizontal = ({ document, authors }: any) => {
  const [mounted, setMounted] = useState(false);
  const fallbackImage = "/images/blklight-thumb.jpg";

  let image;

  if (document.cover || document.imageHeader) {
    image = document.cover ? document.cover : document.imageHeader;
  } else {
    image = fallbackImage;
  }

  return (
    <div className="card card-plain hover:hover-card hover:hover-card-uv hover:dark:hover-card-neon-yellow">
      <div className="card-body !p-5">
        <div className="lg:flex">
          <div className="shrink-0">
            <img
              src={image}
              className={` ${document.filter} lg:w-[300px] w-full lg:h-[275px] h-[300px] object-cover rounded-lg`}
              alt={`${document.title} image`}
            />
          </div>
          <div className="grow md:py-1 py-2 md:px-6">
            <div className="flex flex-wrap items-center">
              <span className="dark:text-light-500 text-lg font-medium text-dark-500">
                <DateFormat date={document.date} fulldate />
              </span>
            </div>

            <h3 className="card-title text-3xl">
              <Link className="" href={document.slug}>
                <span className=" dark:text-light-500 text-dark-500 hover:underline underline-offset-1">
                  {document.title}
                </span>
              </Link>
            </h3>

            {document.description && (
              <p className="text-dark-500 dark:text-light-500 text-lg mb-2">
                {document.description}
              </p>
            )}
            <div className="flex flex-wrap items-center my-2">
              <div className="flex items-center leading-normal !text-base mr-2">
                <span className="marker-line rounded-md !py-1 bg-dark-500 text-light-500 dark:bg-light-500 dark:text-dark-500 capitalize font-medium">
                  {document.channel}
                </span>
              </div>

              <div className="flex items-center leading-normal !text-base">
                <span className="marker-line rounded-md !py-1 bg-dark-500 text-light-500 dark:bg-light-500 dark:text-dark-500 capitalize font-medium">
                  {document.category}
                </span>
              </div>
            </div>
            {document.tags && (
              <div className="flex gap-2 items-center mb-2">
                {document.tags.map((tag: any) => (
                  <Tags key={tag} tag={tag} />
                ))}
              </div>
            )}
            <div className="flex mt-auto">
              {authors.map((author: any) => (
                <div key={author.name} className="flex items-center my-1">
                  <div className="shrink-0">
                    <Tooltip>
                      <TooltipTrigger asChild>
                        <img
                          id={`anchor-${author.slug}-${document.slug}`}
                          src={author.avatar}
                          className="w-[50px] h-[50px] object-cover rounded-full border border-dark-500 mr-2"
                          alt={`${author.name} avatar`}
                        />
                      </TooltipTrigger>
                      <TooltipContent align="center" side="right">
                        <p>{author.name}</p>
                      </TooltipContent>
                    </Tooltip>
                  </div>
                </div>
              ))}

              <div className="flex flex-1 items-center">
                <Link className="ml-auto" href={document.slug}>
                  <button className="tracking-wider text-light-500 dark:text-dark-500 bg-uv-500 dark:bg-neon-yellow-500 hover:ring-2 ring-uv-300 dark:ring-neon-yellow-200 py-1.5 px-3 rounded-md font-medium transition-all !text-base">
                    Ler mais...
                  </button>
                </Link>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default CardHorizontal;
